---

- name: install OpenHPC repository
  yum:
    name: "{{ slurmdbd_ohpc_version }}"
  tags: slurm

- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - slurm-slurmdbd-ohpc
  tags: slurm

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ slurmdbd_user }}"
    group: "{{ slurmdbd_group }}"
    mode: 0755
  loop:
    - "{{ slurmdbd_logdir }}"
    - /etc/slurm
  tags: slurm

- name: copy configuration
  template:
    src: slurmdbd.conf
    dest: /etc/slurm/slurmdbd.conf
    owner: "{{ slurmdbd_user }}"
    group: "{{ slurmdbd_group }}"
    mode: 0600
  notify: restart slurmdbd
  tags: slurm

- name: enable and start service
  service:
    name: slurmdbd
    state: started
    enabled: yes
  tags: slurm
